'use client'

export const CatalogCategorySlugs = {
  TIPO_DEMANDA: 'tipo_demanda',
  ORIGEM_DEMANDA: 'origem_demanda',
  PRIORIDADE_NIVEL: 'prioridade_nivel',
  STATUS_DEMANDA: 'status_demanda',
  TIPO_USUARIO: 'tipo_usuario',
  CARGO_USUARIO: 'cargo_usuario',
  SEGMENTO_CLIENTE: 'segmento_cliente',
  TIPO_ANEXO: 'tipo_anexo',
  IDENTIFICACAO_ORIGEM: 'identificacao_origem',

  STATUS_TRIAGEM: 'status_triagem',
  IMPACTO_NIVEL: 'impacto_nivel',
  URGENCIA_NIVEL: 'urgencia_nivel',
  COMPLEXIDADE_NIVEL: 'complexidade_nivel',
  MOTIVO_ARQUIVAMENTO: 'motivo_arquivamento',
  TIPO_SOLICITACAO_INFO: 'tipo_solicitacao_info',

  STATUS_DISCOVERY: 'status_discovery',
  SEVERIDADE_PROBLEMA: 'severidade_problema',
  IMPACTO_INSIGHT: 'impacto_insight',
  CONFIANCA_INSIGHT: 'confianca_insight',
  STATUS_INSIGHT: 'status_insight',
  STATUS_HIPOTESE: 'status_hipotese',
  IMPACTO_HIPOTESE: 'impacto_hipotese',
  PRIORIDADE_HIPOTESE: 'prioridade_hipotese',
  METODO_PESQUISA: 'metodo_pesquisa',
  STATUS_PESQUISA: 'status_pesquisa',
  TIPO_EVIDENCIA: 'tipo_evidencia',
  TIPO_EXPERIMENTO: 'tipo_experimento',
  STATUS_EXPERIMENTO: 'status_experimento',
  DECISAO_DISCOVERY: 'decisao_discovery',
  DECISAO_FINAL_DISCOVERY: 'decisao_final_discovery',
  METRICA_SUCESSO_DISCOVERY: 'metrica_sucesso_discovery',
  PERSONA_PARTICIPANTE: 'persona_participante',
  PUBLICO_ALVO: 'publico_alvo',

  PLANEJAMENTO_EPICO_STATUS: 'planejamento_epico_status',
  PLANEJAMENTO_EPICO_HEALTH: 'planejamento_epico_health',
  PLANEJAMENTO_FEATURE_STATUS: 'planejamento_feature_status',
  PLANEJAMENTO_DEPENDENCIA_TIPO: 'planejamento_dependencia_tipo',
  PLANEJAMENTO_DEPENDENCIA_RISCO: 'planejamento_dependencia_risco',
  PLANEJAMENTO_COMMITMENT_TIER: 'planejamento_commitment_tier',
  PLANEJAMENTO_CENARIO_STATUS: 'planejamento_cenario_status',
  PLANEJAMENTO_SQUAD_STATUS: 'planejamento_squad_status',
  PLANNING_CYCLE_STATUS: 'planning_cycle_status',

  AUTOMACAO_CAMPOS: 'automacao_campos',
  AUTOMACAO_OPERADORES: 'automacao_operadores',
  AUTOMACAO_ACOES: 'automacao_acoes',

  CATALOGO_TAGS: 'catalogo_tags',
  FRAMEWORKS_PRIORIZACAO: 'frameworks_priorizacao',
  TEMPLATES_NOTIFICACAO: 'templates_notificacao',
  TIPOS_WORKFLOW: 'tipos_workflow',
  CAMPOS_CUSTOMIZADOS: 'campos_customizados',
  INTEGRACOES_EXTERNAS: 'integracoes_externas',
} as const

export type CatalogCategorySlug = (typeof CatalogCategorySlugs)[keyof typeof CatalogCategorySlugs]

export const catalogSlugLabels: Record<CatalogCategorySlug, string> = {
  [CatalogCategorySlugs.TIPO_DEMANDA]: 'Tipos de demanda',
  [CatalogCategorySlugs.ORIGEM_DEMANDA]: 'Origens de demanda',
  [CatalogCategorySlugs.PRIORIDADE_NIVEL]: 'Prioridades',
  [CatalogCategorySlugs.STATUS_DEMANDA]: 'Status da demanda',
  [CatalogCategorySlugs.TIPO_USUARIO]: 'Tipo de usuário',
  [CatalogCategorySlugs.CARGO_USUARIO]: 'Cargo do usuário',
  [CatalogCategorySlugs.SEGMENTO_CLIENTE]: 'Segmento de cliente',
  [CatalogCategorySlugs.TIPO_ANEXO]: 'Tipos de anexo',
  [CatalogCategorySlugs.IDENTIFICACAO_ORIGEM]: 'Origem identificada',

  [CatalogCategorySlugs.STATUS_TRIAGEM]: 'Status da triagem',
  [CatalogCategorySlugs.IMPACTO_NIVEL]: 'Impacto',
  [CatalogCategorySlugs.URGENCIA_NIVEL]: 'Urgência',
  [CatalogCategorySlugs.COMPLEXIDADE_NIVEL]: 'Complexidade',
  [CatalogCategorySlugs.MOTIVO_ARQUIVAMENTO]: 'Motivos de arquivamento',
  [CatalogCategorySlugs.TIPO_SOLICITACAO_INFO]: 'Tipo de solicitação de informação',

  [CatalogCategorySlugs.STATUS_DISCOVERY]: 'Status do discovery',
  [CatalogCategorySlugs.SEVERIDADE_PROBLEMA]: 'Severidade do problema',
  [CatalogCategorySlugs.IMPACTO_INSIGHT]: 'Impacto do insight',
  [CatalogCategorySlugs.CONFIANCA_INSIGHT]: 'Confiança do insight',
  [CatalogCategorySlugs.STATUS_INSIGHT]: 'Status do insight',
  [CatalogCategorySlugs.STATUS_HIPOTESE]: 'Status da hipótese',
  [CatalogCategorySlugs.IMPACTO_HIPOTESE]: 'Impacto da hipótese',
  [CatalogCategorySlugs.PRIORIDADE_HIPOTESE]: 'Prioridade da hipótese',
  [CatalogCategorySlugs.METODO_PESQUISA]: 'Métodos de pesquisa',
  [CatalogCategorySlugs.STATUS_PESQUISA]: 'Status da pesquisa',
  [CatalogCategorySlugs.TIPO_EVIDENCIA]: 'Tipos de evidência',
  [CatalogCategorySlugs.TIPO_EXPERIMENTO]: 'Tipos de experimento',
  [CatalogCategorySlugs.STATUS_EXPERIMENTO]: 'Status do experimento',
  [CatalogCategorySlugs.DECISAO_DISCOVERY]: 'Decisão do discovery',
  [CatalogCategorySlugs.DECISAO_FINAL_DISCOVERY]: 'Decisão final do discovery',
  [CatalogCategorySlugs.METRICA_SUCESSO_DISCOVERY]: 'Métricas de sucesso',
  [CatalogCategorySlugs.PERSONA_PARTICIPANTE]: 'Personas participantes',
  [CatalogCategorySlugs.PUBLICO_ALVO]: 'Público afetado',
  [CatalogCategorySlugs.PLANEJAMENTO_EPICO_STATUS]: 'Status de épicos',
  [CatalogCategorySlugs.PLANEJAMENTO_EPICO_HEALTH]: 'Saúde de épicos',
  [CatalogCategorySlugs.PLANEJAMENTO_FEATURE_STATUS]: 'Status de features',
  [CatalogCategorySlugs.PLANEJAMENTO_DEPENDENCIA_TIPO]: 'Tipos de dependência',
  [CatalogCategorySlugs.PLANEJAMENTO_DEPENDENCIA_RISCO]: 'Risco de dependência',
  [CatalogCategorySlugs.PLANEJAMENTO_COMMITMENT_TIER]: 'Tiers de commitment',
  [CatalogCategorySlugs.PLANEJAMENTO_CENARIO_STATUS]: 'Status de cenários',
  [CatalogCategorySlugs.PLANEJAMENTO_SQUAD_STATUS]: 'Status de squad (Planejamento)',
  [CatalogCategorySlugs.PLANNING_CYCLE_STATUS]: 'Status de planning cycle',

  [CatalogCategorySlugs.AUTOMACAO_CAMPOS]: 'Campos para automação',
  [CatalogCategorySlugs.AUTOMACAO_OPERADORES]: 'Operadores de automação',
  [CatalogCategorySlugs.AUTOMACAO_ACOES]: 'Ações de automação',

  [CatalogCategorySlugs.CATALOGO_TAGS]: 'Catálogo de tags',
  [CatalogCategorySlugs.FRAMEWORKS_PRIORIZACAO]: 'Frameworks de priorização',
  [CatalogCategorySlugs.TEMPLATES_NOTIFICACAO]: 'Templates de notificação',
  [CatalogCategorySlugs.TIPOS_WORKFLOW]: 'Tipos de workflow',
  [CatalogCategorySlugs.CAMPOS_CUSTOMIZADOS]: 'Campos customizados',
  [CatalogCategorySlugs.INTEGRACOES_EXTERNAS]: 'Integrações externas',
}
